[package]
name = "student_system"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
async_trait = "0.1.88"

[lib]
path = "lib.rs"