[package]
name = "student_system"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.88"
thiserror = "2.0.12"

[lib]
path = "lib.rs"