//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "course_prerequisites")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub course_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub prerequisite_course_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses2,
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::PrerequisiteCourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses1,
}

impl ActiveModelBehavior for ActiveModel {}
