//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::sea_orm_active_enums::CurriculumType;
use sea_orm::entity::prelude::*;
use sea_orm::JsonValue;

use super::facilities;
use crate::users::infrastructure::db::users;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "courses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub code: String,
    pub name: String,
    pub section: i32,
    pub curriculum: CurriculumType,
    pub capacity: i32,
    pub credits: i32,
    pub teacher_id: String,
    pub facility_id: String,
    pub cycle: i32,
    pub enrolled: i32,
    pub prerequisites: JsonValue,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::course_schedules::Entity")]
    CourseSchedules,

    #[sea_orm(
        belongs_to = "facilities::Entity",
        from = "Column::FacilityId",
        to = "facilities::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Facilities,

    #[sea_orm(
        belongs_to = "users::Entity",
        from = "Column::TeacherId",
        to = "users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::course_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseSchedules.def()
    }
}

impl Related<facilities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Facilities.def()
    }
}

impl Related<users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
