//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::course_prerequisites::Entity as CoursePrerequisites;
pub use super::course_schedules::Entity as CourseSchedules;
pub use super::courses::Entity as Courses;
