//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "curriculum_type")]
pub enum CurriculumType {
    #[sea_orm(string_value = "M2015")]
    M2015,
    #[sea_orm(string_value = "M2018")]
    M2018,
    #[sea_orm(string_value = "M2023")]
    M2023,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "day_type")]
pub enum DayType {
    #[sea_orm(string_value = "Lunes")]
    Lunes,
    #[sea_orm(string_value = "Martes")]
    Martes,
    #[sea_orm(string_value = "Miércoles")]
    MiRcoles,
    #[sea_orm(string_value = "Jueves")]
    Jueves,
    #[sea_orm(string_value = "Viernes")]
    Viernes,
    #[sea_orm(string_value = "Sábado")]
    SBado,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "session_type")]
pub enum SessionType {
    #[sea_orm(string_value = "Teoría")]
    TeorA,
    #[sea_orm(string_value = "Práctica")]
    PrCtica,
    #[sea_orm(string_value = "Laboratorio")]
    Laboratorio,
}
