pub mod completed_courses;
pub mod delete;
pub mod enrollment_attempts;
pub mod find_by_student_and_course;
pub mod save;
pub mod total_credits_enrolled;
pub mod repository;
pub mod find_by_id;
pub mod current_enrollments;