[package]
name = "shared"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
sea-orm = "1.1.12"
tokio = { version = "1", features = ["full"] }

[lib]
path = "lib.rs"